# Highly divisible triangular number

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''
import math

def count_divisor(n):
    limit = int(math.sqrt(n))
    divisors_list = []
    for i in range(1, limit+1, 1):
        if n % i == 0:
            divisors_list.append(i)
            if i != n/i:
                divisors_list.append(n/i)
    return len(divisors_list)

def get_triangle_n(n):
	return value * (value+1) //2

value = 50
while count_divisor(get_triangle_n(value)) < 500:
	value += 1
	print(get_triangle_n(value))
	print(count_divisor(get_triangle_n(value)))
	print('')

print('-----')
print('final value:')	
print(value)


